apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://174.37.17.188:8001
  name: optumera
contexts:
- context:
    cluster: optumera
    namespace: calc-backend
    user: user4
  name: optumera-context
current-context: optumera-context
kind: Config
preferences: {}
users:
- name: optumera-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZGQwZGU2ODU0ZmJjOTdmYTY3Nzg0NWZmMjUyZGJhM2M4NmYxNmUyYyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjQiLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDc4NTM2OCwiaWF0IjoxNTYwNzU2NTY4LCJzdWIiOiJ1c2VyNCIsInRlYW1Sb2xlTWFwcGluZ3MiOlsiaWNwOnVzZXItNDphZG1pbiIsImljcDpkZWZhdWx0Om1lbWJlciIsImljcDpkZWZhdWx0OnRlYW1hZG1pbiJdfQ.iMeZL8CQVb4JhwkcgRGPCQ0FC3PktHRHlBKSkcQsEOZQk_47VLLHr-aaNJ86yN2xQ1UgEq5G52-v79yaC9LYlEU8uIJtbHmVdo0p7_DRPFlEkvErN9bzlaAsXrkQ7_ggeh38QG6TaCVYQYw2dGWn-Lqkz22hOcbcG4HJqE45nnKt-Z6eTS_i6AjXc0CECEaL5JL46lcFMOSD2sMOV3gonxcxAW4nPISLI5PaHdHmxmE0r9N2rcZuJy-_Ew0E5i6HTZiuxeTpkeHFsheDRThafUX6TavvJ4KrBApkHYqdvpT06zyu9BKIdZ1MzdI591TwhZwzVtPhyM4bMDKa27kIJg
- name: user4
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiYTI5OGEzMTA3MzNjNWE2M2M3NDU3NjRmM2U5YjhmZjNmYmM5NzA4OSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjQiLCJpc3MiOiJodHRwczovL29wdHVtZXJhLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiI2MTkxMTQ4YjE2ZDdhNWI1MTRjNzQyMGE2NGE2NmZkNSIsImV4cCI6MTU2MDg4NTgxMywiaWF0IjoxNTYwODU3MDEzLCJzdWIiOiJ1c2VyNCIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.lrr0bD5U6W5h8CHtr0rO5klV-hhC0shSJoIJIp8sBR7N1d9fKi0W6ZnXGu_ZTLpwPPMXJCfSBldUWjNtAS_WYoNuIbaYaqL4E9wzqA6VX3fSgR1_0e31kvyY3_e-0oI2MwecEuZTHMGofUkh449HiQXA8Ps7KjkNFIa3uqMRARQjgdGgZTRm6SK4edMuUwUzp4AkNKzy20maAOYj_0Nz50-hKIDJpKRdfFdYuVqpVC-u48wFIKzdt2_XpeIoIxK1OWP8vP15UFcICCwDaLLMuzwqvxuKuH1whBrpA9-FhwsdMXSz_q3I6fsGsGyWq0jjeROTjOBeJJHL-qgg1bNXig
